### ISSUE TITLE
I can't get work this demo

### ISSUE THREAD

**Issue by wuchtig** [nezamy/view#3]
`
@{
    $pageName = 'home page';
}@

@section('pageTitle'){{ $pageName }}@end
`

I get a Notice:  Undefined variable: pageName

Can you verify this please?

**Comment by nezamy** [comment]
Hello @wuchtig, Thank you for using this library.
in the first hand, you have a typo in `@EnD` you should write `@end`
if that not solve the problem send me the full code including the layout

would you use the route library with the view library?
You can take a look at this repo https://github.com/nezamy/just

**Comment by wuchtig** [comment]
Thank you for your quick response. 
The typo `@end` was my mistake when writing the issue. Sorry

I just follow your tutorial. It seems like the var is out of scope.

[view-test.zip](https://github.com/nezamy/view/files/5294653/view-test.zip)

Thanks a lot in advance.

**Comment by nezamy** [comment]
Yes, You are right there is a bug
The variables passed from the controller should be work fine inside all sections, also the variables you will create inside the section should work inside the same section.
but maybe you need to make variable outside and make it available to all section 
you should use the `ViewBag()` Method like this.
and in any section, you can use  $ViewBag as an array contains all variables you defined 

let's say you defined this in the index.php
```php
$view = new System\Views\View;
$view->view('home', ['content' => 'Here the content passed from Controller']);
```
and home.php
```
@{
    $this->ViewBag('pageName', 'home page');
}@
@section('pageTitle'){{ $ViewBag['pageName'] }}@end
@section('content')
<h2>Hello it`s come from view file</h2>
<p>{{ $content }}</p>
@end
@section('scripts')
<script>
// scripts for this page only 

</script>
@end
```

**Comment by wuchtig** [comment]
Many thanks for your explanation. This makes sense.

btw there are some typos in the README.md

Installition  ->  Installation

`$this->ViewBag('pageName', ''home page'');`  ->  `$this->ViewBag('pageName', 'home page');`

**Comment by nezamy** [comment]
I edited the README.md. Thank you.
